[platformio]
src_dir = 07_Firmware_Implementation/src
include_dir = 07_Firmware_Implementation/include

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    tanakamasayuki/EspUsbHost @ ^2.5.2

build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0